import { StyleSheet, Dimensions } from "react-native";
import Colors from '../config/colors'
//const windowHeight = Dimensions.get("window").height;
const windowWidth = Dimensions.get("window").width;
const windowheight = Dimensions.get("window").height;
const windowwidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;
//const windowWidth = Dimensions.get("window").width;
const SLIDER_WIDTH = Dimensions.get("window").width;
const SLIDE_WIDTH = Math.round((SLIDER_WIDTH * 98) / 100);
const itemHorizontalMargin = (2 * SLIDER_WIDTH) / 100;
const ITEM_WIDTH = SLIDE_WIDTH + itemHorizontalMargin * 2;
const ITEM_HEIGHT = Math.round((ITEM_WIDTH * 2) / 3);
const galleryGridWidth = Math.floor((windowWidth - 10) / 4);
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  chooseCatContainer: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
    marginBottom: 5,
    marginTop: 5,
  },
  imageContainer: {
    borderColor: "#ccc",
    borderWidth: 1,
    padding: 3,
    backgroundColor: "#fff",
    borderRadius: 3,
  },
  image: {
    height: 40,
    width: 40,
  },
  defaultImgIcon: {
    fontSize: 40,
    color: "#adadad",
  },
  name: {
    color: Colors.labelColor,
    // lineHeight: 40,
    fontSize: Colors.lableSize,
    paddingLeft: 4,
    height: "auto",
    paddingVertical: 10,
  },
  buttonsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    marginVertical: 30,
  },
  inputText: {
    backgroundColor: "#fff",
    height: "auto",
    flexWrap: "wrap",
    fontSize: Colors.textSize,
    color: Colors.textColor,
    textAlign: "left",
    padding: 5,
  },
  inputTextArea: {
    backgroundColor: "#fff",
    height: "auto",
    flexWrap: "wrap",
    fontSize: Colors.textSize,
    width: "60%",
    color: Colors.textColor,
    textAlign: "left",
    padding: 5,
  },
  inputContainer: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderColor: "#ddd",
    borderBottomWidth: 1,
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
  },
  pb0: {
    paddingBottom: 0,
  },
  mb0: {
    marginBottom: 0,
  },
  buttonText: {
    fontSize: Colors.textSize,
    fontWeight: "bold",
  },
  saveBtnText: {
    color: Colors.primary,
  },
  exitBtnText: {
    color: Colors.activeTab,
  },
  item: {
    height: 35,
    backgroundColor: "#00b386",
    alignItems: "center",
    justifyContent: "center",
  },
  itemtitle: {
    color: "#fff",
    textAlign: "center",
    fontSize: Colors.textSize,
  },
  errorText: {
    textAlign: "right",
    color: Colors.tomato,
    fontWeight: "bold",
    fontStyle: "italic",
  },
  coverImg: {
    height: 40,
    width: 170,
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  chooseCatContainer: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
    marginBottom: 5,
    marginTop: 5,
  },
  imageContainer: {
    borderColor: "#ccc",
    borderWidth: 1,
    padding: 3,
    backgroundColor: "#fff",
    borderRadius: 3,
  },
  image: {
    height: 50,
    width: 50,
  },
  coverImg: {
    height: 40,
    width: 170,
  },
  defaultImgIcon: {
    fontSize: 40,
    color: "#adadad",
  },
  name: {
    color: Colors.labelColor,
    // lineHeight: 40,
    fontSize: Colors.lableSize,
    paddingLeft: 4,
    height: "auto",
    paddingVertical: 10,
  },
  buttonsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    marginVertical: 30,
  },
  inputText: {
    height: 50,
    // borderColor: "#ccc",
    // borderWidth: 1,
    fontSize: Colors.textSize,
    // backgroundColor: "#f9f6f6",
    paddingHorizontal: 10,
    color: Colors.textColor,
  },
  inputTextArea: {
    // backgroundColor: "#fff",
    // height: 'auto',

    // fontSize: 12,
    // color: Colors.textColor,
    // textAlign: "right",
    // padding: 5,
    width: "60%",
    // borderColor: "#ccc",
    // borderWidth: 1,
    fontSize: Colors.textSize,
    // backgroundColor: "#f9f6f6",
    alignItems: "center",
    paddingHorizontal: 10,
    color: Colors.textColor,
  },
  inputContainer: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderColor: "#ddd",
    borderBottomWidth: 1,
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
  },
  pb0: {
    paddingBottom: 0,
  },
  mb0: {
    marginBottom: 0,
  },
  buttonText: {
    fontSize: Colors.textSize,
    fontWeight: "bold",
  },
  saveBtnText: {
    color: Colors.primary,
  },
  exitBtnText: {
    color: Colors.activeTab,
  },
  mandatory: {
    color: Colors.tomato,
    fontSize: Colors.textSize,
    fontWeight: "bold",
  },
  errorText: {
    textAlign: "right",
    color: Colors.tomato,
    fontWeight: "bold",
    fontStyle: "italic",
  },
  qrCodeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
  },
  downloadBtn: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 3,
    marginLeft: 20,

  },
  qtyContainer: {
    height: 35,
    width: 35,
    borderRadius: 100,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  qty: {
    fontSize: 14,
    color: "#FFF",
  },
  iconStyle: {
    fontSize: 18,
    color: "#cecece",
  },
  image: {
    width: 100,
    height: 100,
  },
  para: {
    marginBottom: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: "bold",
  },
  text: {
    fontSize: 14,
  },
  activeTab: {
    backgroundColor: Colors.activeTab,
    height: 40,
    marginVertical: 5,
    borderRadius: 2,
    marginHorizontal: 5,
  },
  activeText: {
    color: Colors.white,
  },
  inActiveTab: {
    backgroundColor: Colors.inactiveTab,
    height: 40,
    marginVertical: 5,
    borderRadius: 2,
    marginHorizontal: 5,
  },
  inActiveText: {
    color: Colors.white,
  },
  underlineStyle: { backgroundColor: "transparent" },
  scrollableTab: {
    backgroundColor: Colors.white,
    borderWidth: 0,
    borderColor: "#FFF",
  },
  searchModalOverlay: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.white,
    width: windowWidth,
    height: windowHeight,
  },
  seacrhModalContainer: {
    flex: 1,
    backgroundColor: Colors.white,
    width: windowWidth,
    height: windowHeight,
    elevation: 5,
  },
  searchModalHeader: {
    height: 55,
    width: "100%",
    elevation: 5,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: Colors.primary,
  },
  searchBackBtn: {
    width: "15%",
    height: 55,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  searchContainer: {
    width: "85%",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  searchFieldBox: {
    width: "100%",
    height: 40,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0, 0.1)",
    borderRadius: 50,
  },
  searchField: {
    width: "90%",
    padding: 5,
    color: Colors.white,
    fontSize: 15,
  },
  searchModalBody: {
    flex: 1,
    height: windowHeight - 55,
  },
  name: {
    fontSize: 18,
    color: Colors.textColor,
  },
  subText: {
    color: Colors.textColor,
    opacity: 0.8,
    fontSize: 14,

  },
  iconContainer: {
    width: "15%",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  rightAngelIcon: {
    fontSize: 18,
    color: "#cecece",
  },
  floatingBtn: {
    alignItems: "center",
    backgroundColor: Colors.primary,
    width: 50,
    height: 50,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    borderRadius: 50 / 2,
    position: "absolute",
    bottom: 20,
    right: 20,
  },
  floatingBtnText: {
    fontSize: 28,
    color: Colors.white,
    position: "absolute",
    top: 8,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalBody: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    width: Math.floor((windowWidth * 70) / 100),
    minHeight: Math.floor(windowHeight / 4),
    padding: 15,
    borderRadius: 3,
    elevation: 5,
  },
  downloadBtn: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 3,
  },
  loadingText: {
    fontSize: 14,
    color: Colors.textColor,
    opacity: 0.6,
    marginTop: 10,
  },
  closeBtn: {
    position: "absolute",
    bottom: 10,
    padding: 10,
  },
  closeBtnText: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.tomato,
  },
  searchModalOverlay: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.white,
    width: windowWidth,
    height: windowHeight,
  },
  seacrhModalContainer: {
    flex: 1,
    backgroundColor: Colors.white,
    width: windowWidth,
    height: windowHeight,
    elevation: 5,
  },
  searchModalHeader: {
    height: 55,
    width: "100%",
    elevation: 5,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: Colors.primary,
  },
  inputHours: {
    backgroundColor: "#fff",
    height: 'auto',

    fontSize: 12,
    color: Colors.textColor,
    textAlign: "right",
    padding: 5,
  },

  inputBoxComment: {
    flexDirection: "row",
    marginRight: 15,
    marginLeft: 15,
  },

  inputComment: {
    backgroundColor: "#fff",
    height: 'auto',

    fontSize: 12,
    color: Colors.textColor,
    textAlign: "right",
    width: "55%",
    padding: 5,
  },

  avatarPlace: {
    width: 120,
    height: 100,
    backgroundColor: Colors.lightGrey,
    marginTop: 5,
    justifyContent: "center",
    alignItems: "center",
  },

  avatar: {
    position: "absolute",
    width: 120,
    height: 120,
    borderWidth: 1,
    borderColor: "#D3D3D3",
  },
  button: {
    // backgroundColor: Colors.blueBg,
    borderColor: Colors.blueBg,
    borderWidth: 2,
    height: 20,
    width: 20,
    left: windowwidth - 250,
    top: 20,
    borderRadius: 3,
    marginBottom: 50
  },

  image: {
    height: 100,
    width: 100,
    borderWidth: 1,
    borderColor: "#D3D3D3",
  },
  name: {
    marginTop: 20,
    color: "#808080",
    marginBottom: 20,
    textAlign: "center",
  },

  inputBox: {
    alignItems: 'center',
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#fff",
    height: 'auto',
    justifyContent: "space-between",
    marginBottom: 5,
    marginTop: 5,
  },

  input: {
    color: Colors.textColor,
    lineHeight: 40,
    fontSize: 14,
    paddingLeft: 4,
  },


  inputDateTime: {
    backgroundColor: "#fff",
    height: 'auto',

    fontSize: 12,
    color: Colors.textColor,
    textAlign: "right",
    padding: 5,
  },

  profile: {

  },
  pl12: {
    paddingLeft: 12,
  },
  pr12: {
    paddingRight: 12,
  },
  btnContainer: {
    paddingTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  btn: {
    // width: Math.floor(windowWidth / 2),
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  imgContainer: {
    width: "20%",
  },
  image: {
    width: 40,
    height: 40,
    resizeMode: 'contain'


  },
  title: {
    width: "72%",
    fontSize: 16,
    color: Colors.textColor,
  },
  view: {
    height: 70,
    width: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shadwEffect: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.00,
  },
  slide: {
    width: SLIDE_WIDTH,
    height: ITEM_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    resizeMode: 'cover',

  },
  sliderImage: {
    height: ITEM_HEIGHT,
    width: ITEM_WIDTH,

  },
  carouselConatainer: {
    marginBottom: 0,
    position: 'relative',
    height: ITEM_HEIGHT,



  },
  funFactsContainer: {
    width: windowWidth,
    height: 120,
    paddingHorizontal: 8,
    marginTop: 2,
  },
  funFactsBgImage: {
    width: windowWidth - 16,
    height: 120,
  },
  funtFatcsHeading: {
    fontSize: 14,
    fontWeight: "bold",
    color: Colors.lightBrown,
    position: "absolute",
    top: 0,
    left: 20,
  },
  funFactsTextContainer: {
    position: "absolute",
    top: 25,
    left: 40,
    width: Math.floor(windowWidth * 0.6),
    height: 70,
  },
  funFactsText: {
    fontSize: 12,
    color: Colors.black,
  },
  name: {
    fontSize: 12,
    color: Colors.textColor,
  },
  carouselConatainer: {
    marginBottom: 0,
    position: "relative",
    height: ITEM_HEIGHT,
    backgroundColor: "#ff00",
  },
  slide: {
    width: SLIDE_WIDTH,
    height: ITEM_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
    resizeMode: "cover",
  },
  sliderImage: {
    height: ITEM_HEIGHT,
    width: ITEM_WIDTH,
  },

  container_commonName: {
    flex: 1,
    width: windowWidth,
    backgroundColor: Colors.white,
  },
  noCoverImage: {
    width: "100%",
    height: 200,
    backgroundColor: "#c9c9c9",
    alignItems: "center",
    justifyContent: "center",
  },
  svgContainer: {
    width: windowWidth,
    height: 200,
    backgroundColor: Colors.primary,
    justifyContent: "flex-end",
  },
  avatarContainer: {
    position: "absolute",
    padding: 3,
    top: 20,
    left: Math.floor((windowWidth - 150) / 2),
    backgroundColor: Colors.yellowBg,
    borderRadius: 100,
  },
  image: {
    width: 150,
    height: 150,
    borderRadius: 100,
  },
  countContainerLeft: {
    position: "absolute",
    bottom: 5,
    left: 5,
    paddingRight: 10,
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: 5,
    borderRadius: 2,
  },
  countContainerRight: {
    position: "absolute",
    bottom: 5,
    right: 5,
    paddingRight: 10,
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: 5,
    borderRadius: 2,
  },
  countTextBtn: {
    flexDirection: "row",
    alignSelf: "flex-end",
    paddingVertical: 0,
  },
  countText: {
    color: Colors.white,
    fontSize: 14,
  },
  commonName: {
    fontSize: 20,
    fontWeight: "bold",
    color: Colors.chocolate,
    alignSelf: "center",
    lineHeight: 35,
  },
  scientificName: {
    fontSize: 14,
    color: Colors.lightBrown,
    alignSelf: "center",
    fontStyle: "italic",
  },
  descriptionText: {
    color: Colors.textColor,
    fontSize: 12,
    marginTop: 10,
    marginBottom: 10,
    textAlign: "center",
  },
  infoRow: {
    flexDirection: "row",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  w50: {
    width: "50%",
    justifyContent: "center",
  },
  infoTitle: {
    fontWeight: "bold",
    fontSize: 12,
    color: Colors.textColor,
  },
  infoDesc: {
    fontSize: 12,
    color: Colors.textColor,
  },
  iconBoxContainer: {
    marginTop: 10,
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  iconBox: {
    width: 45,
    height: 45,
    backgroundColor: "#eeeeee",
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  activeIconBox: {
    backgroundColor: "#c9c9c9",
  },
  iconBoxImage: {
    width: 28,
    height: 28,
  },
  funFactsContainer: {
    width: windowWidth,
    height: 150,
    paddingHorizontal: 8,
    marginTop: 10,
  },
  funFactsBgImage: {
    width: windowWidth - 16,
    height: 150,
  },
  funtFatcsHeading: {
    fontSize: 14,
    fontWeight: "bold",
    color: Colors.lightBrown,
    position: "absolute",
    top: 12,
    left: 20,
  },
  funFactsTextContainer: {
    position: "absolute",
    top: 43,
    left: 40,
    width: Math.floor(windowWidth * 0.6),
    height: 70,
  },
  funFactsText: {
    fontSize: 12,
    color: Colors.black,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalBody: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    width: windowWidth - 30,
    minHeight: Math.floor(windowHeight / 4),
    padding: 15,
    borderRadius: 3,
    elevation: 8,
  },
  closeButton: {
    position: "absolute",
    zIndex: 11,
    top: 5,
    right: 5,
    backgroundColor: "#ddd",
    width: 25,
    height: 25,
    borderRadius: 40 / 2,
    alignItems: "center",
    justifyContent: "center",
    elevation: 0,
  },
  closeButtonText: {
    color: "#444",
    fontSize: 22,
  },
  btn: {
    flexDirection: "row",
    backgroundColor: Colors.primary,
    borderRadius: 3,
    padding: 10,
    margin: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  animalCountBtn: {
    flexDirection: "row",
    width: 200,
    height: 35,
    marginBottom: 20,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
    borderRadius: 3,
  },
  animalCountBtnText: {
    fontSize: 16,
    color: Colors.white,
  },
  mb0: {
    marginBottom: 0,
  },
  tabComponent: {
    paddingTop: 10,
  },
  ttl: {
    width: "40%",
    fontWeight: "bold",
    fontSize: 16,
    color: Colors.textColor,
  },
  desc: {
    width: "60%",
    fontSize: 15,
    color: Colors.textColor,
    marginBottom: 10,
  },
  galleryContainer: {
    height: 120,
    marginTop: 15,
    paddingHorizontal: 4,
  },
  imageGrid: {
    height: 120,
    width: 88,
    borderRadius: 3,
    // marginHorizontal: 4,
  },
  videoGrid: {
    height: 120,
    width: 88,
    borderRadius: 3,
    marginHorizontal: 4,
    backgroundColor: "#d1d1d1",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadBtn: {
    width: "100%",
    height: 45,
    backgroundColor: Colors.primary,
    borderRadius: 3,
    marginVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  uploadModalBody: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    width: Math.floor((windowWidth * 70) / 100),
    minHeight: Math.floor(windowHeight / 4),
    padding: 15,
    borderRadius: 3,
    elevation: 5,
  },
  loaderContainer: {
    paddingTop: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    fontSize: 14,
    color: "#444",
    opacity: 0.6,
    marginTop: 10,
  },
  closeBtn: {
    position: "absolute",
    bottom: 10,
    padding: 10,
  },
  closeBtnText: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.tomato,
  },
  progressText: {
    marginTop: 10,
    color: Colors.textColor,
    fontSize: 14,
    fontWeight: "bold",
  },
  abortBtn: {
    marginTop: 15,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  abortBtnText: {
    fontSize: 18,
    color: Colors.tomato,
    fontWeight: "bold",
  },
  playbackModalBody: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000",
    width: windowWidth,
    height: windowHeight,
    padding: 15,
    borderRadius: 3,
    elevation: 5,
  },
  video: {
    alignSelf: "center",
    width: "100%",
    height: Math.floor(windowHeight / 4),
  },
  imageBox: {
    width: Math.floor((windowWidth - 32) / 3),
    height: 60,
    backgroundColor: "#f0f0f0",
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  housingGrid: {
    width: Math.floor((windowWidth - 46) / 4),
    alignItems: "center",
  },
  housingImgBox: {
    width: Math.floor((windowWidth - 46) / 4),
    height: 60,
    backgroundColor: "#f0f0f0",
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 5,
  },
  housingImage: {
    width: 30,
    height: 30,
  },
  housingImgTitle: {
    color: Colors.textColor,
    fontSize: 12,
  },
  housingImgSubText: {
    color: Colors.textColor,
    fontSize: 11,
    opacity: 0.7,
  },
  downloadBtn: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 3,
  },
  container_category: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 5,
  },
  view: {
    height: 50,
    flexDirection: "row",
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
    paddingHorizontal: 5,
  },
  name: {
    fontSize: 18,
    color: Colors.textColor,
  },
  rightSection: {
    width: "15%",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  qtyContainer: {
    height: 25,
    width: 25,
    borderRadius: 100,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  qty: {
    fontSize: 14,
    color: "#FFF",
  },
  rightAngelIcon: {
    fontSize: 18,
    color: "#cecece",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalBody: {
    backgroundColor: Colors.white,
    width: windowWidth - 30,
    minHeight: Math.floor(windowHeight / 4),
    borderRadius: 3,
    elevation: 5,
    paddingBottom: 8,
  },
  centerAlign: {
    alignItems: "center",
    justifyContent: "center",
  },
  headerContainer: {
    width: "100%",
    height: 50,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    paddingHorizontal: 8,
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    color: Colors.textColor,
  },
  closeButton: {
    backgroundColor: "#ddd",
    width: 25,
    height: 25,
    borderRadius: 40 / 2,
    alignItems: "center",
    justifyContent: "center",
    elevation: 0,
  },
  closeButtonText: {
    color: Colors.textColor,
    fontSize: 22,
  },
  bodyRow: {
    width: "100%",
    paddingVertical: 5,
    paddingHorizontal: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bodyText: {
    fontSize: 16,
    color: Colors.textColor,
  },
  loadingTextConatiner: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontSize: 14,
    color: Colors.textColor,
    opacity: 0.8,
  },
  searchModalOverlay: {
    justifyContent: "center",
    alignItems: "center",
    width: windowWidth,
    height: windowHeight,
  },
  seacrhModalContainer: {
    flex: 1,
    width: windowWidth,
    height: windowHeight,
    backgroundColor: Colors.white,
  },
  searchModalHeader: {
    height: 55,
    width: "100%",
    elevation: 5,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: Colors.primary,
  },
  backBtnContainer: {
    width: "10%",
    height: 55,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  searchContainer: {
    width: "90%",
    height: 55,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  searchFieldBox: {
    width: "100%",
    height: 40,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0, 0.1)",
    borderRadius: 50,
  },
  searchField: {
    padding: 5,
    width: "90%",
    color: Colors.white,
    fontSize: 15,
  },
  searchModalBody: {
    flex: 1,
    height: windowHeight - 55,
  },
  searchingText: {
    fontSize: 12,
    color: Colors.textColor,
    opacity: 0.8,
    alignSelf: "center",
    marginTop: 20,
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 5,
  },
  view: {
    height: 50,
    flexDirection: "row",
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
    paddingHorizontal: 5,
  },
  name: {
    fontSize: 18,
    color: Colors.textColor,
  },
  rightSection: {
    width: "15%",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  qtyContainer: {
    height: 25,
    width: 25,
    borderRadius: 100,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  qty: {
    fontSize: 14,
    color: "#FFF",
  },
  rightAngelIcon: {
    fontSize: 18,
    color: "#cecece",
  },
  searchModalOverlay: {
    justifyContent: "center",
    alignItems: "center",
    width: windowWidth,
    height: windowHeight,
  },
  seacrhModalContainer: {
    flex: 1,
    width: windowWidth,
    height: windowHeight,
    backgroundColor: Colors.white,
  },
  searchModalHeader: {
    height: 55,
    width: "100%",
    elevation: 5,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: Colors.primary,
  },
  backBtnContainer: {
    width: "10%",
    height: 55,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  searchContainer: {
    width: "90%",
    height: 55,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  searchFieldBox: {
    width: "100%",
    height: 40,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0, 0.1)",
    borderRadius: 50,
  },
  searchField: {
    padding: 5,
    width: "90%",
    color: Colors.white,
    fontSize: 15,
  },
  searchModalBody: {
    flex: 1,
    height: windowHeight - 55,
  },
  searchingText: {
    fontSize: 12,
    color: Colors.textColor,
    opacity: 0.8,
    alignSelf: "center",
    marginTop: 20,
  },
  placeholderStyle: {
    fontSize: 18,
    color: Colors.textColor,
    opacity: 0.8,
  },
  selectedItemsContainer: {
    width: "60%",
    height: "auto",
    paddingVertical: 15,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
  },
  placeHolderContainer: {
    borderWidth: 0,
  },
  errorText: {
    textAlign: "right",
    color: Colors.tomato,
    fontWeight: "bold",
    fontStyle: "italic",
  },
  errorFieldBox: {
    borderWidth: 1,
    borderColor: Colors.tomato,
  },
  buttonsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    marginVertical: 30,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: "bold",
  },
  saveBtnText: {
    color: Colors.primary,
  },
  exitBtnText: {
    color: Colors.activeTab,
  },
  fieldBox: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
    marginBottom: 5,
    marginTop: 5,
    // shadowColor: "#999",
    // shadowOffset: {
    // 	width: 0,
    // 	height: 1,
    // },
    // shadowOpacity: 0.22,
    // shadowRadius: 2.22,
    // elevation: 3,
  },
  labelName: {
    color: Colors.labelColor,
    // lineHeight: 40,
    fontSize: 19,
    paddingLeft: 4,
    height: "auto",
    paddingVertical: 10,
  },
  textfield: {
    backgroundColor: "#fff",
    height: "auto",

    fontSize: 12,
    color: Colors.textColor,
    textAlign: "right",
    padding: 5,
    width: "60%",
  },
  button: {
    alignItems: "center",
    backgroundColor: Colors.primary,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    borderRadius: 20,
    color: "#fff",
    marginVertical: 10,
    zIndex: 0,
  },
  dropdownTextField: {
    backgroundColor: "#fff",
    height: "auto",

    fontSize: 18,
    color: Colors.textColor,
    textAlign: "center",
    padding: 5,
    width: "50%",
  },
  multiSelectContainer: {
    height: 'auto',
    width: '100%',
    borderRadius: 3,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#fff",
    marginBottom: 5,
    marginTop: 5,
    shadowColor: "#999",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    padding: 5,
  },
  placeholderStyle: {
    fontSize: 18,
    color: Colors.textColor,
    opacity: 0.8,
  },
  body: {
    flex: 9,
    padding: 2,
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 1,
  },
  view: {
    flexDirection: "row",
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  image: {
    width: 50,
    height: 50,
  },
  name: {
    fontSize: 18,
    color: Colors.textColor,
    marginBottom: 8,
  },
  qtyContainer: {
    height: 35,
    width: 35,
    borderRadius: 100,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  qty: {
    fontSize: 14,
    color: "#FFF",
  },
  btns: {
    fontSize: 18,
    color: Colors.white,
  },
  angelIconContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  iconStyle: {
    fontSize: 18,
    color: "#cecece",
  },
  searchModalOverlay: {
    justifyContent: "center",
    alignItems: "center",
    width: windowWidth,
    height: windowHeight,
  },
  seacrhModalContainer: {
    flex: 1,
    width: windowWidth,
    height: windowHeight,
    backgroundColor: Colors.white,
  },
  searchModalHeader: {
    height: 55,
    width: "100%",
    elevation: 5,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: Colors.primary,
  },
  backBtnContainer: {
    width: "10%",
    height: 55,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  searchBackground: {
    backgroundColor: Colors.primary,
  },
  searchContainer: {
    backgroundColor: Colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 3,
    padding: 5,
    marginTop: -5,
    marginBottom: 5,
    marginHorizontal: 8,
  },
  dateContainer: {
    borderWidth: 1,
    borderColor: Colors.primary,
    borderRadius: 3,
    paddingVertical: 5,
    marginTop: 5,
    paddingHorizontal: 15,
    marginHorizontal: 15,
  },
  searchFieldBox: {
    width: "100%",
    height: 40,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0, 0.1)",
    borderRadius: 50,
  },
  searchField: {
    padding: 5,
    width: "90%",
    color: Colors.white,
    fontSize: 15,
  },
  searchModalBody: {
    flex: 1,
    height: windowHeight - 55,
  },
  searchingText: {
    fontSize: 12,
    color: Colors.textColor,
    opacity: 0.8,
    alignSelf: "center",
    marginTop: 20,
  },

  popupContainer: {
    backgroundColor: "#fff",
    paddingTop: 20,
    paddingBottom: 20,
    width: windowWidth - 40,
  },
  popupText: {
    fontSize: 16,
    color: Colors.black,
    alignSelf: "center",
  },
  pb0: {
    paddingBottom: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  mb0: {
    marginBottom: 0,
  },
  wrapper: {
    borderWidth: 1,
    borderColor: "#e5e5e5",
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 3,
    width: "100%",
    // marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },

  fieldBox: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
  },
  labelName: {
    color: Colors.labelColor,
    // lineHeight: 40,
    // fontSize: 19,
    // paddingLeft: 4,
    height: "auto",
    // paddingVertical: 10,
  },
  textfield: {
    backgroundColor: "#fff",
    height: "auto",
    flexWrap: "wrap",
    fontSize: 19,
    color: Colors.textColor,
    textAlign: "right",
    padding: 5,
  },
  dateField: {
    backgroundColor: "#fff",
    height: "auto",
    flexWrap: "wrap",
    fontSize: 19,
    color: Colors.textColor,
    textAlign: "left",
    width: "22%",
    padding: 5,
  },
  buttonsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    marginVertical: 30,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: "bold",
  },
  saveBtnText: {
    color: Colors.primary,
  },
  exitBtnText: {
    color: Colors.activeTab,
  },
  feedButton: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 1,
    paddingVertical: 5,
    borderRadius: 3,
  },
  allocFeedButton: {
    width: "18%",
    height: 35,
    alignItems: "center",
    marginHorizontal: 2,
    justifyContent: "center",
    paddingHorizontal: 1,
    paddingVertical: 5,
    borderRadius: 3,
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 8
  },
  feedBoxfull: {
    flexDirection: "row",
  },
  feedBox: {
    justifyContent: "center",
    alignItems: 'center',
    height: 50,
    width: "22%",
    padding: 5,
    borderRadius: 6,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#EFF0E8",
    lineHeight: 50,
    marginBottom: 5,
    textAlign: "center",
    marginTop: 5,
    marginLeft: 5,
    marginRight: 5,
    shadowColor: "#999",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  feedBoxTime: {
    justifyContent: "center",
    alignItems: 'center',
    height: 50,
    width: "22%",
    padding: 5,
    borderRadius: 6,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#fff",
    lineHeight: 50,
    marginBottom: 5,
    textAlign: "center",
    marginTop: 5,
    marginLeft: 5,
    marginRight: 5,
    shadowColor: "#999",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  feedfield: {
    textAlign: "center",
    color: "#555"
  },
  textRed: {
    textAlign: "center",
    color: Colors.tomato,
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 1,
  },
  view: {
    flexDirection: "row",
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  image: {
    width: 50,
    height: 50,
  },
  name: {
    fontSize: 18,
    color: Colors.textColor,
    marginBottom: 8,
  },
  qtyContainer: {
    height: 35,
    width: 35,
    borderRadius: 100,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  qty: {
    fontSize: 14,
    color: "#FFF",
  },
  btns: {
    fontSize: 18,
    color: Colors.white,
  },
  angelIconContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  iconStyle: {
    fontSize: 18,
    color: "#cecece",
  },
  searchModalOverlay: {
    justifyContent: "center",
    alignItems: "center",
    width: windowWidth,
    height: windowHeight,
  },
  seacrhModalContainer: {
    flex: 1,
    width: windowWidth,
    height: windowHeight,
    backgroundColor: Colors.white,
  },
  searchModalHeader: {
    height: 55,
    width: "100%",
    elevation: 5,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: Colors.primary,
  },
  backBtnContainer: {
    width: "10%",
    height: 55,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  searchBackground: {
    backgroundColor: Colors.primary,
  },
  searchContainer: {
    backgroundColor: Colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 3,
    padding: 5,
    marginTop: -5,
    marginBottom: 5,
    marginHorizontal: 8,
  },
  dateContainer: {
    borderWidth: 1,
    borderColor: Colors.primary,
    borderRadius: 3,
    paddingVertical: 5,
    marginTop: 5,
    paddingHorizontal: 15,
    marginHorizontal: 15,
  },
  searchFieldBox: {
    width: "100%",
    height: 40,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0, 0.1)",
    borderRadius: 50,
  },
  searchField: {
    padding: 5,
    width: "90%",
    color: Colors.white,
    fontSize: 15,
  },
  searchModalBody: {
    flex: 1,
    height: windowHeight - 55,
  },
  searchingText: {
    fontSize: 12,
    color: Colors.textColor,
    opacity: 0.8,
    alignSelf: "center",
    marginTop: 20,
  },

  popupContainer: {
    backgroundColor: "#fff",
    paddingTop: 20,
    paddingBottom: 20,
    width: windowWidth - 40,
  },
  popupText: {
    fontSize: 16,
    color: Colors.black,
    alignSelf: "center",
  },
  pb0: {
    paddingBottom: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  mb0: {
    marginBottom: 0,
  },
  wrapper: {
    borderWidth: 1,
    borderColor: "#e5e5e5",
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 3,
    width: "100%",
    // marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },

  fieldBox: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
  },
  labelName: {
    color: Colors.labelColor,
    // lineHeight: 40,
    fontSize: 19,
    paddingLeft: 4,
    height: "auto",
    paddingVertical: 10,
  },
  textfield: {
    backgroundColor: "#fff",
    height: "auto",
    flexWrap: "wrap",
    fontSize: 19,
    color: Colors.textColor,
    textAlign: "right",
    padding: 5,
  },
  dateField: {
    backgroundColor: "#fff",
    height: "auto",
    flexWrap: "wrap",
    fontSize: 19,
    color: Colors.textColor,
    textAlign: "left",
    width: "22%",
    padding: 5,
  },
  buttonsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    marginVertical: 30,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: "bold",
  },
  saveBtnText: {
    color: Colors.primary,
  },
  exitBtnText: {
    color: Colors.activeTab,
  },
  feedButton: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 1,
    paddingVertical: 5,
    borderRadius: 3,
  },
  allocFeedButton: {
    width: "18%",
    height: 35,
    alignItems: "center",
    marginHorizontal: 2,
    justifyContent: "center",
    paddingHorizontal: 1,
    paddingVertical: 5,
    borderRadius: 3,
  },
  fieldBox: {
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderColor: "#ddd",
    borderWidth: 1,
    backgroundColor: "#fff",
    height: 50,
    justifyContent: "space-between",
    marginBottom: 5,
    marginTop: 5,
    shadowColor: "#999",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  textfield: {
    backgroundColor: "#fff",
    height: 40,

    fontSize: 12,
    color: Colors.textColor,
    textAlign: "right",
    width: "60%",
    padding: 5,
  },
  textfielddate: {
    backgroundColor: "#fff",
    height: 40,
    lineHeight: 30,
    fontSize: 12,
    color: Colors.textColor,
    textAlign: "left",
    width: "50%",
    padding: 5,
    fontWeight: "bold",
  },
  button: {
    alignItems: "center",
    backgroundColor: Colors.primary,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    borderRadius: 20,
    color: "#fff",
    marginVertical: 10,
  },
  textWhite: {
    color: "#fff",
    fontWeight: "bold",
  },
  labelName: {
    color: Colors.textColor,
    lineHeight: 40,
    fontSize: 14,
    paddingLeft: 4,
  },
  textInputIcon: {
    position: "absolute",
    bottom: 14,
    right: 10,
    marginLeft: 8,
    color: "#0482ED",
    zIndex: 99,
  },
  errorFieldBox: {
    borderWidth: 1,
    borderColor: Colors.tomato,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalBody: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    width: Math.floor((windowWidth * 60) / 100),
    minHeight: Math.floor(windowHeight / 5),
    padding: 15,
    borderRadius: 3,
    elevation: 5,
  },
  downloadBtn: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 3,
  },
  loadingText: {
    fontSize: 14,
    color: "#444",
    opacity: 0.6,
    marginTop: 10,
  },
  closeBtn: {
    position: "absolute",
    bottom: 10,
    padding: 10,
  },
  closeBtnText: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.tomato,
  },
  searchModalOverlay: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.white,
    width: windowWidth,
    height: windowHeight,
  },
  seacrhModalContainer: {
    flex: 1,
    backgroundColor: Colors.white,
    width: windowWidth,
    height: windowHeight,
    elevation: 5,
  },
  searchModalHeader: {
    height: 55,
    flexDirection: "row",
    width: "100%",
    backgroundColor: Colors.primary,
    elevation: 1,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  headerBackBtnContainer: {
    width: "20%",
    height: 55,
    paddingLeft: 8,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  headerTitleContainer: {
    width: "80%",
    height: 55,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  searchModalBody: {
    flex: 1,
    height: windowHeight - 55,
    padding: 6,
  },
  searchingText: {
    fontSize: 12,
    color: Colors.textColor,
    opacity: 0.8,
    alignSelf: "center",
    marginTop: 20,
  },
  listItemContainer: {
    flexDirection: "row",
    paddingHorizontal: 6,
    paddingVertical: 5,
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
  },
  titleText: {
    fontSize: 16,
    color: Colors.textColor,
  },
  subText: {
    color: Colors.textColor,
    opacity: 0.8,
    fontSize: 14,

  },
  angelIconContainer: {
    width: "15%",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  rightAngelIcon: {
    fontSize: 18,
    color: "#cecece",
  },
  pl12: {
    paddingLeft: 12,
  },
  pr12: {
    paddingRight: 12,
  },
  btnContainer: {
    paddingTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  btn: {
    // width: Math.floor(windowWidth / 2),
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  imgContainer: {
    width: "20%",
  },
  image: {
    width: 40,
    height: 40,
    resizeMode: "contain",
  },
  title: {
    width: "72%",
    fontSize: 16,
    color: Colors.textColor,
  },
  view: {
    height: 70,
    width: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  shadwEffect: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
  },
  slide: {
    width: SLIDE_WIDTH,
    height: ITEM_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
    resizeMode: "cover",
  },
  sliderImage: {
    height: ITEM_HEIGHT,
    width: ITEM_WIDTH,
  },
  carouselConatainer: {
    marginBottom: 0,
    position: "relative",
    height: ITEM_HEIGHT,
  },
  funFactsContainer: {
    width: windowWidth,
    height: 120,
    paddingHorizontal: 8,
    marginTop: 2,
  },
  funFactsBgImage: {
    width: windowWidth - 16,
    height: 120,
  },
  funtFatcsHeading: {
    fontSize: 14,
    fontWeight: "bold",
    color: Colors.lightBrown,
    position: "absolute",
    top: 0,
    left: 20,
  },
  funFactsTextContainer: {
    position: "absolute",
    top: 25,
    left: 40,
    width: Math.floor(windowWidth * 0.6),
    height: 70,
  },
  funFactsText: {
    fontSize: 12,
    color: Colors.black,
  },
  name: {
    fontSize: 12,
    color: Colors.textColor,
  },

  modalbox: {
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 10,
    height: "100%",
    justifyContent: "center",
  },
  scrollViewStyle: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    height: "100%",
  },
  modalbody: {
    backgroundColor: Colors.white,
    // height: 150,
    // maxHeight: parseInt(windowHeight / 3),
    bottom: 0,
    padding: 10,
    marginHorizontal: 30,
    color: Colors.black,
    borderRadius: 4,
    paddingVertical: 20,
  },
  modalTitleStyle: {
    textAlign: "center",
    fontSize: 20,
    marginBottom: 22,
  },
  modalTextStyle: {
    textAlign: "center",
    // fontSize: 20,
    marginBottom: 22,
  },
  modalImageStyle: {
    height: 250,
    textAlign: "center",
    width: 250,
    // marginHorizontal: "auto",
  },
  closeButton: {
    position: "absolute",
    zIndex: 11,
    top: 3,
    right: 3,
    backgroundColor: "#007968",
    width: 30,
    height: 30,
    borderRadius: 40 / 2,
    alignItems: "center",
    justifyContent: "center",
    elevation: 0,
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 26,
  },
  view: {
    flexDirection: "row",
    height: 50,
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
    paddingHorizontal: 5,
  },
  name: {
    fontSize: 18,
    color: Colors.textColor,
  },
  iconStyle: {
    fontSize: 18,
    color: "#cecece",
  },
  container: {
    height: windowHeight,
    width: windowWidth,
    backgroundColor: Colors.lightGrey,
    alignItems: "center",
    justifyContent: "center",
    padding: 15,
  },
  fieldBox: {
    width: "100%",
    flexDirection: "row",
    borderRadius: 3,
    borderColor: Colors.primary,
    borderWidth: 1,
    height: 50,
    justifyContent: "space-between",
    marginVertical: 12,
  },
  textfield: {
    width: "100%",
    height: 50,
    paddingHorizontal: 8,
    fontSize: 16,
    color: Colors.textColor,
  },
  eyeBtn: {
    position: "absolute",
    top: 10,
    right: 1,
    padding: 3,
  },
  button: {
    width: "100%",
    alignItems: "center",
    backgroundColor: Colors.primary,
    padding: 10,
    shadowColor: Colors.lightGrey,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    borderRadius: 20,
    marginTop: 15,
  },
  textWhite: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  errorText: {
    fontSize: 14,
    color: Colors.tomato,
    fontWeight: "bold",
  },
  errorFieldBox: {
    borderWidth: 1,
    borderColor: Colors.tomato,
  },
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  pl12: {
    paddingLeft: 12,
  },
  pr12: {
    paddingRight: 12,
  },
  btnContainer: {
    paddingTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  btn: {
    // width: Math.floor(windowWidth / 2),
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  imgContainer: {
    width: "20%",
  },
  image: {
    width: 40,
    height: 40,
    resizeMode: "contain",
  },
  title: {
    width: "72%",
    fontSize: 16,
    color: Colors.textColor,
  },
  view: {
    height: 70,
    width: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  shadwEffect: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
  },
  slide: {
    width: SLIDE_WIDTH,
    height: ITEM_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
    resizeMode: "cover",
  },
  sliderImage: {
    height: ITEM_HEIGHT,
    width: ITEM_WIDTH,
  },
  carouselConatainer: {
    marginBottom: 0,
    position: "relative",
    height: ITEM_HEIGHT,
  },
  funFactsContainer: {
    width: windowWidth,
    height: 120,
    paddingHorizontal: 8,
    marginTop: 2,
  },
  funFactsBgImage: {
    width: windowWidth - 16,
    height: 120,
  },
  funtFatcsHeading: {
    fontSize: 14,
    fontWeight: "bold",
    color: Colors.lightBrown,
    position: "absolute",
    top: 0,
    left: 20,
  },
  funFactsTextContainer: {
    position: "absolute",
    top: 25,
    left: 40,
    width: Math.floor(windowWidth * 0.6),
    height: 70,
  },
  funFactsText: {
    fontSize: 12,
    color: Colors.black,
  },
  name: {
    fontSize: 12,
    color: Colors.textColor,
  },

  modalbox: {
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 10,
    height: "100%",
    justifyContent: "center",
  },
  scrollViewStyle: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    height: "100%",
  },
  modalbody: {
    backgroundColor: Colors.white,
    // height: 150,
    // maxHeight: parseInt(windowHeight / 3),
    bottom: 0,
    padding: 10,
    marginHorizontal: 30,
    color: Colors.black,
    borderRadius: 4,
    paddingVertical: 20,
  },
  modalTitleStyle: {
    textAlign: "center",
    fontSize: 20,
    marginBottom: 22,
  },
  modalTextStyle: {
    textAlign: "center",
    // fontSize: 20,
    marginBottom: 22,
  },
  modalImageStyle: {
    height: 250,
    textAlign: "center",
    width: 250,
    // marginHorizontal: "auto",
  },
  closeButton: {
    position: "absolute",
    zIndex: 11,
    top: 3,
    right: 3,
    backgroundColor: "#007968",
    width: 30,
    height: 30,
    borderRadius: 40 / 2,
    alignItems: "center",
    justifyContent: "center",
    elevation: 0,
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 26,
  },
  container: {
    height: windowHeight,
    width: windowWidth,
    backgroundColor: Colors.lightGrey,
    alignItems: "center",
    justifyContent: "center",
    padding: 15,
  },
  fieldBox: {
    width: "100%",
    flexDirection: "row",
    borderRadius: 3,
    borderColor: Colors.primary,
    borderWidth: 1,
    height: 50,
    justifyContent: "space-between",
    marginVertical: 12,
  },
  textfield: {
    width: "100%",
    height: 50,
    paddingHorizontal: 8,
    fontSize: 16,
    color: Colors.textColor,
  },
  eyeBtn: {
    position: "absolute",
    top: 10,
    right: 1,
    padding: 3,
  },
  button: {
    width: "100%",
    alignItems: "center",
    backgroundColor: Colors.primary,
    padding: 10,
    shadowColor: Colors.lightGrey,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    borderRadius: 20,
    marginTop: 15,
  },
  textWhite: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  errorText: {
    fontSize: 14,
    color: Colors.tomato,
    fontWeight: "bold",
  },
  errorFieldBox: {
    borderWidth: 1,
    borderColor: Colors.tomato,
  },
  Homecontainer: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  pl12: {
    paddingLeft: 12,
  },
  pr12: {
    paddingRight: 12,
  },
  btnContainer: {
    paddingTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  btn: {
    // width: Math.floor(windowWidth / 2),
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  imgContainer: {
    width: "20%",
  },
  image: {
    width: 40,
    height: 40,
    resizeMode: "contain",
  },
  title: {
    width: "72%",
    fontSize: 16,
    color: Colors.textColor,
  },
  view: {
    height: 70,
    width: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  shadwEffect: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
  },
  slide: {
    width: SLIDE_WIDTH,
    height: ITEM_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
    resizeMode: "cover",
  },
  sliderImage: {
    height: ITEM_HEIGHT,
    width: ITEM_WIDTH,
  },
  carouselConatainer: {
    marginBottom: 0,
    position: "relative",
    height: ITEM_HEIGHT,
  },
  funFactsContainer: {
    width: windowWidth,
    height: 120,
    paddingHorizontal: 8,
    marginTop: 2,
  },
  funFactsBgImage: {
    width: windowWidth - 16,
    height: 120,
  },
  funtFatcsHeading: {
    fontSize: 14,
    fontWeight: "bold",
    color: Colors.lightBrown,
    position: "absolute",
    top: 0,
    left: 20,
  },
  funFactsTextContainer: {
    position: "absolute",
    top: 25,
    left: 40,
    width: Math.floor(windowWidth * 0.6),
    height: 70,
  },
  funFactsText: {
    fontSize: 12,
    color: Colors.black,
  },
  name: {
    fontSize: 12,
    color: Colors.textColor,
  },

  modalbox: {
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 10,
    height: "100%",
    justifyContent: "center",
  },
  scrollViewStyle: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    height: "100%",
  },
  modalbody: {
    backgroundColor: Colors.white,
    // height: 150,
    // maxHeight: parseInt(windowHeight / 3),
    bottom: 0,
    padding: 10,
    marginHorizontal: 30,
    color: Colors.black,
    borderRadius: 4,
    paddingVertical: 20,
  },
  modalTitleStyle: {
    textAlign: "center",
    fontSize: 20,
    marginBottom: 22,
  },
  modalTextStyle: {
    textAlign: "center",
    // fontSize: 20,
    marginBottom: 22,
  },
  modalImageStyle: {
    height: 250,
    textAlign: "center",
    width: 250,
    // marginHorizontal: "auto",
  },
  closeButton: {
    position: "absolute",
    zIndex: 11,
    top: 3,
    right: 3,
    backgroundColor: "#007968",
    width: 30,
    height: 30,
    borderRadius: 40 / 2,
    alignItems: "center",
    justifyContent: "center",
    elevation: 0,
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 26,
  },
  container: {
    flex: 1,
    padding: 8,
  },
  fieldBox: {
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    backgroundColor: "#fff",
    height: 50,
    justifyContent: "space-between",
    marginBottom: 5,
    marginTop: 5,
    shadowColor: "#999",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  textfield: {
    backgroundColor: "#fff",
    height: 40,

    fontSize: 12,
    color: "#444",
    textAlign: "right",
    width: "60%",
    padding: 5,
  },
  labelName: {
    color: "#333",
    lineHeight: 40,
    fontSize: 14,
    paddingLeft: 4,
  },
  button: {
    alignItems: "center",
    backgroundColor: Colors.primary,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    borderRadius: 20,
    color: "#fff",
    marginTop: 10,
  },
  textWhite: {
    color: "#fff",
    fontWeight: "bold",
  },
  errorFieldBox: {
    borderWidth: 1,
    borderColor: Colors.tomato
  },
  errorText: {
    textAlign: "right",
    color: Colors.tomato,
    fontWeight: "bold",
    fontStyle: "italic",
    marginRight: 2,
  },
  submitBtn: {
    width: "96%",
    height: 45,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.primary,
    borderRadius: 50,
    alignSelf: "center",
    marginTop: 25,
  },
  submitBtnText: {
    fontSize: 18,
    color: Colors.white,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalBody: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    width: Math.floor((windowWidth * 70) / 100),
    minHeight: Math.floor(windowHeight / 4),
    padding: 15,
    borderRadius: 3,
    elevation: 5,
  },
  loadingText: {
    fontSize: 14,
    color: "#444",
    opacity: 0.6,
    marginTop: 10,
  },
  closeBtn: {
    position: "absolute",
    bottom: 10,
    padding: 10,
  },
  closeBtnText: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.tomato,
  },
  container_Task: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 8
  },
  row_Task: {
    flexDirection: "row",
    width: "100%",
    height: 50,
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
    alignItems: "center"
  },
  name_Task: {
    fontSize: 18,
    color: "#555",
  },
  iconContainer_Task: {
    flex: 1,
    alignItems: "flex-end"
  },
  iconStyle_Task: {
    fontSize: 18,
    color: '#cecece'
  },
  listContainer_SubSpecies: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 5,
  },
  image_SubSpecies: {
    width: 40,
    height: 40,
    marginLeft: 5,
  },
  view_SubSpecies: {
    flexDirection: "row",
    height: 50,
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
  },
  name_SubSpecies: {
    fontSize: 20,
  },
  qtyContainer: {
    height: 25,
    width: 25,
    borderRadius: 100,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  qty: {
    fontSize: 16,
    color: "#FFF",
  },
  rightAngelIcon_SubSpecies: {
    fontSize: 18,
    color: "#cecece",
  },
  container_SubCategory: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 5,
  },
  view_SubCategory: {
    flexDirection: "row",
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  image_SubCategory: {
    width: 55,
    height: 55,
  },
  name_SubCategory: {
    fontSize: 18,
    color: Colors.textColor,
  },
  qtyContainer_SubCategory: {
    height: 35,
    width: 35,
    borderRadius: 100,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  qty_SubCategory: {
    fontSize: 14,
    color: "#FFF",
  },
  iconStyle_SubCategory: {
    fontSize: 18,
    color: "#cecece",
  },
  slide_SubCategory: {
    width: SLIDE_WIDTH,
    height: ITEM_HEIGHT + 5,
    alignItems: "center",
    justifyContent: "center",
  },
  sliderImage_SubCategory: {
    height: ITEM_HEIGHT,
    width: ITEM_WIDTH,
  },
  carouselConataine_SubCategoryr: {
    marginBottom: 5,
    position: "relative",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    elevation: 1,
    height: ITEM_HEIGHT,
  },
  container_SectionRelations: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 5,
  },
  image_SectionRelations: {
    width: 40,
    height: 40,
    marginLeft: 5,
  },
  view_SectionRelations: {
    flexDirection: "row",
    // height: 50,
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
    padding: 5,
  },
  titleText_SectionRelations: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#444",
  },
  subText_SectionRelations: {
    fontSize: 15,
    color: "#444",
    opacity: 0.8,
    fontWeight: "normal",
  },
  iconBox_SectionRelations: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  iconStyle_SectionRelations: {
    fontSize: 18,
    color: "#cecece",
  },
  listContainer_Species: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 5,
  },
  image: {
    width: 40,
    height: 40,
    marginLeft: 5,
  },
  viewr_Species: {
    flexDirection: "row",
    height: 50,
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
  },
  name_Species: {
    fontSize: 20,
  },
  qtyContainer_Species: {
    height: 25,
    width: 25,
    borderRadius: 100,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  qty_Species: {
    fontSize: 16,
    color: "#FFF",
  },
  arrow_Species: {
    fontSize: 18,
  },
  rightAngelIcon_Species: {
    fontSize: 18,
    color: "#cecece",
  },
});
export default styles;